name: tests

on:
  push:
    branches: [develop, main, master, workos]
  pull_request:
    branches: [develop, main, master, workos]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.4', '8.5']

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: job_site
        options: >-
          --default-authentication-plugin=mysql_native_password
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=10


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, pdo, pdo_mysql

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node Dependencies
        run: npm install

      - name: Install Composer without scripts
        run: composer install --no-interaction --no-scripts --prefer-dist

      # TEMP environment to allow package discovering
      - name: Create temporary safe env
        run: |
          echo "APP_KEY=" > .env
          echo "APP_ENV=ci" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=job_site" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Generate key
        run: php artisan key:generate

      - name: Run composer scripts
        run: composer run-script post-autoload-dump

      # Load final CI env
      - name: Copy CI env
        run: cp .env.ci .env

      # Wait for MySQL (guaranteed)
      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysql -h mysql -uroot -proot -e "SELECT 1"; do
            echo "MySQL not ready yet..."
            sleep 2
          done

      # Extra wait for stability
      - name: Extra DB wait
        run: sleep 5

      - name: Run migrations
        run: php artisan migrate --force

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: ./vendor/bin/pest
